# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ffe32386397c271dec0cc19cc91b979372c074e9fbe7ef8835fd23af910c28d7c0dc344b7773456bdaf3e2aad1d74ee7c3682070cfa8ed9436db7493ca86cdf

test:
  secret_key_base: 8a4438b2a3b9b2f25bdef2afba695005ac3f9ecde547f4d9074303904d05c8ab6491b3db2e6fc8ffb450793b8b57ed182c7dcf5088924128539c19bf358830d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
